language: python
dist: xenial
sudo: required
cache:
- apt
addons:
  apt:
    packages:
    - nginx
    - curl
    - wget
    - ruby
    - ruby-dev
install:
- sudo gem install inspec
- sudo curl -sL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- sudo unzip -d /usr/local/bin /tmp/terraform.zip
- sudo gem install bundler
- bundle install
script:
- terraform fmt
- terraform init
- kitchen converge
- kitchen verify
- kitchen destroy
env:
  global:
    secure: sRFc4sY8SL6ijs9MUZNnyWM8KYZV2wqzKLvXO9XLjuy1eojlann6Js7kZO9gqIlcDHLytaZLqtoW5TSReMTSMlfC6HBPrmX1G8wm2OXTTCFfDU31ZOdG3/tKhHQsQ8v9tyzQ6e0L1/UbEPRVL565e3oyCsrxGBeNI2VzTF3vWxptwFaiI4O2Uiwiqo8C/E8ct/ukQIwqmohYVehBddGr0Zf6igWL0JjDnFJx3axeJquTpWN5rTUUUKx32kbenWikslJg6mOLfu8vEgzWJf4koK8rcYvo+tmSFz0N54U1N4Gn2BfL7Poz7VD55r2Akiir1IUzLC91HSA8y3y3vKWqwXbQ/kJZyZTVtex5d+1cQRdA7AvdMUJQgLfnK/YLXrdpBzGz+l2u7n4KBysiCBN/EffJUEt8eXnOTor3MA4hse+YjR4/q6MIE3Gi1oqAPqbZuPzqrEYh7YeE09Q/vTAAJUDYPVzCfzFiJgHZnl16SATWTcmzTC/kqHONgAiYJBB7yLz/lMy0Sjdy+cduRart4I/4SXHmGk/1oPwis/GCy4xeCRbwN9fyzYKT2FBcT8qN8xHXGzbV+BH49Su5mr7uBzSRN/jBYg2CfEbe/W6pIoCdi8wDIelxOIqLj3UsP9ulsEMmF0xJtS3kJ5fUMIz7BpHRiDZZeSe7drTvbJh/lMI=


